name: tests

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - "pytest_pytorch/**"
      - "tests/**"
      - "pyproject.toml"
      - "pytest.ini"
      - "requirements-dev.txt"
      - "setup.cfg"
      - "tox.ini"
      - ".github/workflows/tests.yml"

  schedule:
    - cron: "0 4 * * *"

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.6', '3.7', '3.8', '3.9']
        include:
          - os: windows-latest
            python: "3.6"
          - os: macos-latest
            python: "3.6"

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox -e tests --notest

      - name: Run tests
        run: tox -e tests
